project:
  type: website
  output-dir: docs

website:
  title: "Jimmy Luc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
    
    right:
      - text: "{{< iconify bi envelope width='24' title='E-mail' >}}"
        href: "mailto:jimmy.luc@mail.utoronto.ca"
      - text: "{{< iconify bi github width='24' title='GitHub' >}}"
        href: https://github.com/rex009x
        rel: me
      - text: "{{< iconify bi linkedin width='24' title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/jimmy-luc-b7446b204/
        rel: me

  page-footer:
    left: |
      @2024 Jimmy Luc</span>
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
